name = "test_doc"
uuid = "7f40b1cc-a26a-43dd-b556-b22c00fd092a"
authors = ["artememelin <artememelin@bootcamp-bhft.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
